:datasett: FKB-Arealbruk
:versjon: 5.1
:skjemaversjon: 5.1
:publisert: 2026-10-05
:metadata-url: https://kartkatalog.geonorge.no/metadata/fkb-arealbruk/87b31015-a3de-4540-9b8b-cb1bf4e1cb3a
:versjon-forrige: 5.0.2
:versjon-erstattet-av: 5.1
:underversjon: 2027-01-01
:underversjon-forrige: 2022-01-01
:dokumentstatus: 2
// All informasjon i hode over denne linja må fylles ut for hvert datasett. 
include::../felles_prodspek/filhode.adoc[]


== Innledning, historikk og endringslogg

=== Innledning
FKB-Arealbruk er en del av Felles Kartdatabase (FKB). FKB-spesifikasjonen er en serie produktspesifikasjoner for detaljerte basis geodata som samles inn og forvaltes gjennom Geovekst. Generelle beskrivelser for alle FKB-spesifikasjonene er samlet i FKB-Generell del <<FKB>>.

FKB-Arealbruk beskriver den fysiske bruken av et areal. Datasettet er ikke heldekkende. 

Markslagsbeskrivelser kartlegges i datasettet FKB-AR5 (arealtilstand, bonitet, markslag og mineralske råstoffer). Arealplandata (kommuneplaner, reguleringsplaner osv.) viser juridiske bestemmelser om hvordan et område skal disponeres. FKB-Arealbruk er viser altså en tredje type kartlegging av et areal der det fokuseres på den fysiske bruken av et geografisk område uavhengig av jordas produksjonsevne eller hva området er planlagt/bestemt brukt til. Eksempl på dette kan være et utbyggingsområde som i FKB-Arealbruk vil kodes som et anleggsområde, uavhengig av om dette arealstykke egner seg som fulldyrka areal og hva området er regulert til i plandataene. 

Mye av detaljinformasjonen om registrering av de ulike objekttypene i FKB er samlet i egne Fotogrammetriske registreringsinstrukser. 

Denne produktspesifikasjonen er utarbeidet iht. SOSI produktspesifikasjoner – Krav og godkjenning 5.0 <<SOSI-KRAV>>. UML-modellen som ligger til grunn for innhold i diagrammene og dokumentasjon i kap. 5, følger reglene i SOSI Regler for UML-modellering, versjon 5.1 <<SOSI-UML>>. http://sosi.geonorge.no/veiledere/UML[Denne veilederen] gir hjelp til å lese UML-diagrammene.

=== Historikk

Tidligere versjoner:

* FKB versjon 3.3 oktober 2001
* FKB versjon 3.4 august 2002
* FKB-Arealbruk versjon 4.0 – 2007-01-01
* FKB-Arealbruk versjon 4.01 - 2009-03-10
* FKB-Arealbruk versjon 4.02 - 2011-12-01
* FKB-Arealbruk versjon 4.6 - 2016-07-01
* FKB-Arealbruk versjon 4.61 - 2018-01-01
* FKB-Arealbruk versjon 5.0 - 2022-01-01
* FKB-Arealbruk versjon 5.0.1 - 2022-01-01
* FKB-Arealbruk versjon 5.0.2 - 2022-01-01

=== Endringslogg

==== Innhold i endringsloggen

FKB 5.0 er en ny hovedversjon av FKB. Dette innebærer at det er gjort større endringer i standarden. Det vil ikke være tilstrekkelig å lese endringsloggen for å få et helhetlig bilde av FKB 5.0 produktspesifikasjonene. For å få et komplett bilde av produktspesifikasjonen må man lese dokumentasjonen som en helhet, inkludert de gjennomgående endringene som er beskrevet i FKB Generell del 5.0 <<FKB>>.

Endringsloggene for det enkelte datasett har som ambisjonsnivå å beskrive de viktigste endringene når det gjelder datainnhold (objekttyper) siden forrige versjon. Endringsloggen vil ikke inneholde alle detaljerte endringer på egenskapsnivå eller endringer når det gjelder utvekslingsformat,  datamodellering eller lignende. 

==== Endringer FKB-Arealbruk versjon 5.0.2 til FKB-Arealbruk 5.1

* Lagt inn Lufthavn som ny objekttype
* Fjernet realisering fra Areal 4.0 (SOSI del 2) som nå er en tilbaketrukket standard
* Oppdatert kap 6 om referansesystem

==== Endringer FKB-Arealbruk versjon 5.0.1 til FKB-Arealbruk 5.0.2

* Lagt inn manglende defaultCodeSpace-tag på egenskapen registreringsversjon i abstrakt featuretype Fellesegenskaper

==== Endringer FKB-Arealbruk versjon 5.0 til FKB-Arealbruk 5.0.1

* Feilretting: Endret mulitiplisitet på eksternpeker fra [1..1] til [0..1] på den abstrakte featuretypen ArealbrukGenerell

==== Endringer fra FKB-Arealbruk versjon 4.61 til FKB-Arealbruk versjon 5.0

* Oppdatert generelle konsepter fra FKB 5.0 generell del
* Alle objekttyper modelleres med heleid flategeometri. Dette innebærer:
** Påkrevd flategeometri og uten opsjonell punktgeometri
** Objekttype Arealbruksgrense og ArealbruksgrenseFiktiv utgår 
** Stedfestingskvalitet kodes på flateobjektet og gjelder da avgrensningen til flate-objektet
* Alle objekttyper modelleres med eksternpeker (mulighet for å legge inn peker - i form av en URI - til objektet i et annet system)
* Objekttype Transformatorstasjon innføres som en ny objekttype

=== Normative referanser

include::../felles_prodspek/kap14_normativ_ref.adoc[]

<<<

== Definisjoner og forkortelser

=== Definisjoner

include::../felles_prodspek/kap21_definisjoner.adoc[]

=== Forkortelser

include::../felles_prodspek/kap22_forkortelser.adoc[]

<<<

== Generelt om spesifikasjonen

=== Unik identifisering
FKBArealbruk

==== Fullstendig navn
{datasett} 

==== Versjon
{versjon}

=== Referansedato
2027-01-01

=== Ansvarlig organisasjon
Geovekst

=== Språk
Norsk

=== Hovedtema
Basisdata, arealbruk

=== Temakategori
basisData

=== Sammendrag
FKB-Arealbruk beskriver fysisk bruk av et geografisk område.

=== Formål
// Fellesdel for FKB generell del og alle FKB-produktspesifikasjoner
include::../felles_prodspek/kap38_formal.adoc[]


// Fellesdel som dekker kap 3.9 - 3.12 for alle FKB-produktspesifikasjoner
include::../felles_prodspek/kap39-312_representasjon.adoc[]

=== Supplerende beskrivelse
Data ikke angitt

<<<

== Spesifikasjonsomfang

include::../felles_prodspek/kap4_omfang.adoc[]  

<<<

== Innhold og struktur

=== Omfang
<<HeleDatasettet,Hele datasettet>>

include::modellRapport.adoc[]

<<<

== Referansesystem

Romlige referansesystem for håndteres likt for alle FKB-datasett. Se https://sosi.geonorge.no/Standarder/FKB_generell_del/#_romlige_referansesystem[Vedlegg B i FKB Generell del] for en beskrivelse.

<<<

== Kvalitet

include::../felles_prodspek/kap7_kvalitet.adoc[]

<<<

== Datafangst

include::../felles_prodspek/kap8_datafangst.adoc[]

<<<

== Datavedlikehold

include::../felles_prodspek/kap9_vedlikehold.adoc[]

<<<

== Presentasjon

=== Omfang
<<HeleDatasettet,Hele datasettet>>

=== Referanse til presentasjonskatalog
Presentasjonsregler for FKB-data er angitt i skjermkartografispesifikasjonen: https://register.geonorge.no/register/versjoner/tegneregler/geovekst/fkb-skjermkartografi

<<<

== Leveranse

include::../felles_prodspek/kap11_leveranse.adoc[]

<<<

== Tilleggsinformasjon
Ingen angitt informasjon

== Metadata

=== Omfang
<<HeleDatasettet,Hele datasettet>>

=== Metadataspesifikasjon

include::../felles_prodspek/kap13_metadata.adoc[]

<<<

[appendix]
== GML-realisering

GML-realiseringen følger kravene i "Realisering i GML-format 5.0" <<SOSI-GML>>. Realiseringen defineres av følgende filer:

* link:{skjema-url}/FKBArealbruk.xsd[GML-Skjema]
* link:{skjema-url}/FKBArealbruk.sch[Schematron-Skjema]
* link:{skjema-url}/eksempel/[Katalog med eksempelfiler]

[appendix]
== SOSI-format-realisering

SOSI-realiseringen følger kravene i "Realisering i SOSI-foramt 5.0" <<SOSI-FORMAT>>. Under en utlisting av SOSI-formatrealiseringen:

include::SOSIformatRealisering.adoc[]

:sectnums!:

<<<

[discrete]
== Lisensvilkår

// Inkl. lisensvilkår
include::../felles_prodspek/lisensvilkaar.adoc[]